### ISSUE TITLE
Add cache-busting for Nginx cache.

### ISSUE THREAD

**Issue by chriswallace** [faithmade/faithmade#10]
We have a plugin that purges the cache when you click the "clear cache" button in the admin bar. We need "on-demand" cache clearing when you save or even preview a post. Right now, previewing post content in Faith Builder is a bit buggy with previewing content. It may even be more related to Amazon S3 because we save out CSS files, so maybe keep those files local until we officially publish. The cache within Nginx is just static html pages saved to folders on the server. Pretty straightforward.

Please look at the Nginx cache plugin we have to find the appropriate function to use to clear individual page caches on save and also figure out if there is something special you need to do for cache clearing when you are previewing a post within Faith Builder.

**Comment by imbradmiller** [comment]
@chriswallace, where does this fall based on priority?

**Comment by garand** [comment]
@christianc1 @chriswallace Any idea what's up with this? Has it already been taken care of?

**Comment by christianc1** [comment]
I've looked at it @garand.  Honestly it's pretty high priority.  It's hard to replicate since it seems to happen sporadically.  If you run into specific issues, try to note the actions and post them here so I can look into them.

**Comment by angela-crist** [comment]
@christianc1 @garand @imbradmiller @chriswallace 
This is included in the 0.9 Release timeframe for Faithmade core.

**Comment by christianc1** [comment]
👍

**Comment by angela-crist** [comment]
@christianc1 Let me know if you think we will have an update for this for Thursday to go with the 0.2 Release of the Faithmade plugin

**Comment by christianc1** [comment]
New cache directives added in v0.2.0, we'll monitor and reopen issue and adjust if necessary.  See e997374e4e746c781dfc9a1de0cb144c107845bf
