### ISSUE TITLE
Gravity Forms - remove extra junk from settings screens

### ISSUE THREAD

**Issue by chriswallace** [faithmade/faithmade#3]
There are a number of strings that reference WordPress. Please change WordPress to Faithmade anywhere you see it in a string.

Also, there is an upgrade/license renewal image that appears on some pages that should be suppressed. Let's kill that. I couldn't find it. Seems like it is encoded or hidden somewhere.

**Comment by christianc1** [comment]
I changed the strings.  Having trouble replicating an upgrade image though.  Can I get some more information @chriswallace?

**Comment by christianc1** [comment]
Reopened until merge
