### ISSUE TITLE
Remove access to plugins menu for anyone but network admin

### ISSUE THREAD

**Issue by chriswallace** [faithmade/faithmade#4]
Can't remove it from the WP network admin (there's a checkbox for it but it doesn't uncheck). Please remove it programmatically. If the user is a network admin, they should still be able to enable/disable plugins for any site.

**Comment by christianc1** [comment]
I need some clarification @chriswallace.

Currently users with the administrator role can see plugins.php if they navigate to Your Account->Premium Features.  

I guess I just don't understand where and for whom you are trying to remove the Plugins Menu.  From what I can see, the typical plugins menu in the sidebar is only available currently to super admins.

**Comment by chriswallace** [comment]
As long as admin users cannot see Plugins, that's what we want. Only superadmins should be able to toggle plugins.

**Comment by christianc1** [comment]
Re open until merge
